default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dataprop_test_development

production:
  <<: *default
  database: dataprop_test_production
  url: <%= ENV['DATABASE_URL'] %>

  # Necesario para Solid Cable en Rails 8
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
